package com.kpi.diploma.perevertailo.model.util.value;

public enum ThemeValues {
    DEFINITION_PROBABILITIES,
    ACTIONS_ON_EVENTS,
    COMPLETE_PROBABILITY,
    FORMULA_BERNULI,
    VARIANCE_OF_RELATIVE_FREQUENCY,
    RANGE_OF_DISTRIBUTION,
    BASIC_LAWS_OF_DISTRIBUTION,
    BASIC_NUMERICAL_CHARACTERISTICS,
    SYSTEMS_OF_TWO_RANDOM_VALUES,
    THE_LAW_OF_LARGE_NUMBERS,
    SELECTIVE_METHOD,
    STATISTICAL_ESTIMATION_OF_PARAMETERS_OF_DISTRIBUTION,
    METHODS_OF_ASSESSMENT_OF_THE_EVALUATION,
    STATISTICAL_CHECK_OF_STATISTICAL_HYPOTHESIS,
}
