package com.kpi.diploma.perevertailo.model.util.value;

public enum ThemeValues {
    DEFINITION_PROBABILITIES,
    ACTIONS_ON_EVENTS,
    COMPLETE_PROBABILITY,
    FORMULA_BERNULI,
    VARIANCE_OF_RELATIVE_FREQUENCY,
    RANGE_OF_DISTRIBUTION,
    BASIC_NUMERICAL_CHARACTERISTICS,
    SYSTEMS_OF_TWO_RANDOM_VALUES,
    SELECTIVE_METHOD,
    STATISTICAL_CHECK_OF_STATISTICAL_HYPOTHESIS,
}
