server:
  port: 8000

spring:
  data:
    mongodb:
      database: theory-of-probability

sendgrid:
  key: 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

logging:
  level:
    spring: INFO
    com:
      kpi:
        diploma: DEBUG

